#### Datos: mapa propuesta de la línea de enrgía (febrero 2026)

El siguiente script tiene como objetivo obtener la información sobre el 


por consumo de energia eléctrica en cada alcaldía de la Ciudad de México. 


Fuente: Censos Económicos 2024


Link: https://www.inegi.org.mx/app/saic/default.html


Link de base de datos: https://docs.google.com/spreadsheets/d/1bCl3Gg9EsDheWaaDr44toIWUFAazgKmABu-uquGKw_o/edit?gid=0#gid=0

Link de consulta de la clasificación de las actividades económicas: https://docs.google.com/spreadsheets/d/1ckOabnLFTHOPRR5vCYwbpKJJH4_MthNgUYycVm6sMP4/edit?gid=0#gid=0

In [2]:
#Se limpia el entorno de trabajo
rm(list=ls())

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, srvyr, openxlsx, readr, janitor, dplyr, stringr, googlesheets4)

In [8]:
# Configurar para que no pida autenticación
gs4_deauth()

# Usar la URL completa de tu hoja de cálculo
datos <- read_sheet("https://docs.google.com/spreadsheets/d/1bCl3Gg9EsDheWaaDr44toIWUFAazgKmABu-uquGKw_o/edit?gid=0#gid=0")

head(datos)

✔ Reading from censos_economicos.

✔ Range Hoja 1.

  Año Censal Entidad             Municipio
1 2023       09 Ciudad de México NA
2 2023       09 Ciudad de México NA
3 2023       09 Ciudad de México NA
4 2023       09 Ciudad de México NA
5 2023       09 Ciudad de México NA
6 2023       09 Ciudad de México NA
  Actividad económica
1 Total estatal
2 Sector 11 Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza
3 Sector 21 Minería
4 Sector 22 Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas natural por ductos al consumidor final
5 Sector 23 Construcción
6 Sector 31-33 Industrias manufactureras
  UE Unidades económicas
1 425005
2     34
3     25
4    118
5   1358
6  31218
  K412A Gasto por consumo de energía eléctrica (millones de pesos)
1 33463.106
2     0.148
3   723.760
4  3696.517
5   310.278
6  5224.887

In [14]:
datos <- datos %>% 
  clean_names() %>% 
  filter(
    actividad_economica != "Total estatal",
    actividad_economica != "Total municipal",
    !is.na(municipio),
    municipio != "",
    !is.na(k412a_gasto_por_consumo_de_energia_electrica_millones_de_pesos),
    actividad_economica != "Sector 11 Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza"
  ) %>% 
  mutate(
    sector = str_extract(actividad_economica, "\\d+(?:-\\d+)?"),
    gran_sector = case_when(
      sector %in% c("11", "21", "22", "23", "31-33") ~ "Industria",
      sector %in% c("43", "46") ~ "Comercio",
      sector %in% c("48-49", "51", "52", "53", "54",
                    "55", "56", "61", "62", "71",
                    "72", "81") ~ "Servicios",
      TRUE ~ NA_character_
    ),
    gasto_miles = k412a_gasto_por_consumo_de_energia_electrica_millones_de_pesos * 1000
  ) %>%
  rename(
    gasto_energia_millones = k412a_gasto_por_consumo_de_energia_electrica_millones_de_pesos
  )

head(datos)

  ano_censal entidad             municipio
1 2023       09 Ciudad de México 002 Azcapotzalco
2 2023       09 Ciudad de México 002 Azcapotzalco
3 2023       09 Ciudad de México 002 Azcapotzalco
4 2023       09 Ciudad de México 002 Azcapotzalco
5 2023       09 Ciudad de México 002 Azcapotzalco
6 2023       09 Ciudad de México 002 Azcapotzalco
  actividad_economica                                ue_unidades_economicas
1 Sector 23 Construcción                               60
2 Sector 31-33 Industrias manufactureras             1519
3 Sector 43 Comercio al por mayor                     721
4 Sector 46 Comercio al por menor                    7430
5 Sector 48-49 Transportes, correos y almacenamiento  139
6 Sector 51 Información en medios masivos              36
  gasto_energia_millones sector gran_sector gasto_miles
1    1.414               23     Industria      1414
2 1143.090               31-33  Industria   1143090
3  335.125               43     Comercio     335125
4  246.202               46     Comercio     246202
5   67.254               48-49  Servicios     67254
6   14.187               51     Servicios     14187

In [11]:
tabla_municipal <- datos %>% 
  group_by(municipio, gran_sector) %>% 
  summarise(
    gasto_total = sum(gasto_miles, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  group_by(municipio) %>% 
  mutate(
    total_municipal = sum(gasto_total),
    participacion = round((gasto_total / total_municipal)*100
  , 2)) %>% 
  ungroup()
tabla_municipal

   municipio                  gran_sector gasto_total total_municipal
1  002 Azcapotzalco           Comercio     581327     2039002
2  002 Azcapotzalco           Industria   1144504     2039002
3  002 Azcapotzalco           Servicios    313171     2039002
4  003 Coyoacán               Comercio     368995     1336251
5  003 Coyoacán               Industria    179536     1336251
6  003 Coyoacán               Servicios    787720     1336251
7  004 Cuajimalpa de Morelos  Comercio     389412     1010347
8  004 Cuajimalpa de Morelos  Industria     47470     1010347
9  004 Cuajimalpa de Morelos  Servicios    573465     1010347
10 005 Gustavo A. Madero      Comercio     404306     1210885
11 005 Gustavo A. Madero      Industria    454639     1210885
12 005 Gustavo A. Madero      Servicios    351940     1210885
13 006 Iztacalco              Comercio     157276      502485
14 006 Iztacalco              Industria    221636      502485
15 006 Iztacalco              Servicios    123573      502485
16 007 Iztapalapa             Comercio     960449     2800579
17 007 Iztapalapa             Industria   1102135     2800579
18 007 Iztapalapa             Servicios    737995     2800579
19 008 La Magdalena Contreras Comercio      41534      111436
20 008 La Magdalena Contreras Industria      7132      111436
21 008 La Magdalena Contreras Servicios     62770      111436
22 009 Milpa Alta             Comercio      11693       27684
23 009 Milpa Alta             Industria      9250       27684
24 009 Milpa Alta             Servicios      6741       27684
25 010 Álvaro Obregón         Comercio     361995     2045439
26 010 Álvaro Obregón         Industria    333606     2045439
27 010 Álvaro Obregón         Servicios   1349838     2045439
28 011 Tláhuac                Comercio      68772      372643
29 011 Tláhuac                Industria    268785      372643
30 011 Tláhuac                Servicios     35086      372643
31 012 Tlalpan                Comercio     306165      772079
32 012 Tlalpan                Industria    104392      772079
33 012 Tlalpan                Servicios    361522      772079
34 013 Xochimilco             Comercio     166134      314573
35 013 Xochimilco             Industria     90406      314573
36 013 Xochimilco             Servicios     58033      314573
37 014 Benito Juárez          Comercio     613217     2142264
38 014 Benito Juárez          Industria    245775     2142264
39 014 Benito Juárez          Servicios   1283272     2142264
40 015 Cuauhtémoc             Comercio     927376     8382723
41 015 Cuauhtémoc             Industria    270278     8382723
42 015 Cuauhtémoc             Servicios   7185069     8382723
43 016 Miguel Hidalgo         Comercio    1737828     5281606
44 016 Miguel Hidalgo         Industria   1030016     5281606
45 016 Miguel Hidalgo         Servicios   2513762     5281606
46 017 Venustiano Carranza    Comercio     232934      784250
47 017 Venustiano Carranza    Industria    263065      784250
48 017 Venustiano Carranza    Servicios    288251      784250
   participacion
1  28.51
2  56.13
3  15.36
4  27.61
5  13.44
6  58.95
7  38.54
8   4.70
9  56.76
10 33.39
11 37.55
12 29.06
13 31.30
14 44.11
15 24.59
16 34.29
17 39.35
18 26.35
19 37.27
20  6.40
21 56.33
22 42.24
23 33.41
24 24.35
25 17.70
26 16.31
27 65.99
28 18.46
29 72.13
30  9.42
31 39.65
32 13.52
33 46.82
34 52.81
35 28.74
36 18.45
37 28.62
38 11.47
39 59.90
40 11.06
41  3.22
42 85.71
43 32.90
44 19.50
45 47.59
46 29.70
47 33.54
48 36.75

In [17]:
promedio_energia <- datos %>% 
  group_by(municipio, gran_sector) %>% 
  summarise(
    gasto_total_miles = sum(gasto_energia_millones * 1000, na.rm = TRUE),
    total_ue = sum(ue_unidades_economicas, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  mutate(
    gasto_promedio_miles_por_ue = if_else(
      total_ue > 0,
      gasto_total_miles / total_ue,
      NA_real_
    )
  ) %>% 
  mutate(gasto_promedio_miles_por_ue = round(gasto_promedio_miles_por_ue, 2))
promedio_energia

   municipio                  gran_sector gasto_total_miles total_ue
1  002 Azcapotzalco           Comercio     581327            8151
2  002 Azcapotzalco           Industria   1144504            1579
3  002 Azcapotzalco           Servicios    313171            7368
4  003 Coyoacán               Comercio     368995           10070
5  003 Coyoacán               Industria    179536            1558
6  003 Coyoacán               Servicios    787720           11020
7  004 Cuajimalpa de Morelos  Comercio     389412            3925
8  004 Cuajimalpa de Morelos  Industria     47470             526
9  004 Cuajimalpa de Morelos  Servicios    573465            3551
10 005 Gustavo A. Madero      Comercio     404306           23576
11 005 Gustavo A. Madero      Industria    454639            3651
12 005 Gustavo A. Madero      Servicios    351940           19582
13 006 Iztacalco              Comercio     157276            7845
14 006 Iztacalco              Industria    221636            1542
15 006 Iztacalco              Servicios    123573            6626
16 007 Iztapalapa             Comercio     960449           45149
17 007 Iztapalapa             Industria   1102135            7667
18 007 Iztapalapa             Servicios    737995           29195
19 008 La Magdalena Contreras Comercio      41534            3913
20 008 La Magdalena Contreras Industria      7132             545
21 008 La Magdalena Contreras Servicios     62770            3256
22 009 Milpa Alta             Comercio      11693            4135
23 009 Milpa Alta             Industria      9250             571
24 009 Milpa Alta             Servicios      6741            2188
25 010 Álvaro Obregón         Comercio     361995           10671
26 010 Álvaro Obregón         Industria    333606            1643
27 010 Álvaro Obregón         Servicios   1349838            9822
28 011 Tláhuac                Comercio      68772            8768
29 011 Tláhuac                Industria    268785            1669
30 011 Tláhuac                Servicios     35086            5917
31 012 Tlalpan                Comercio     306165           11651
32 012 Tlalpan                Industria    104392            1959
33 012 Tlalpan                Servicios    361522           10467
34 013 Xochimilco             Comercio     166134           11358
35 013 Xochimilco             Industria     90406            1390
36 013 Xochimilco             Servicios     58033            6044
37 014 Benito Juárez          Comercio     613217            7616
38 014 Benito Juárez          Industria    245775            1231
39 014 Benito Juárez          Servicios   1283272           12996
40 015 Cuauhtémoc             Comercio     927376           35991
41 015 Cuauhtémoc             Industria    270278            4078
42 015 Cuauhtémoc             Servicios   7185069           23127
43 016 Miguel Hidalgo         Comercio    1737828            8915
44 016 Miguel Hidalgo         Industria   1030016            1491
45 016 Miguel Hidalgo         Servicios   2513762           12090
46 017 Venustiano Carranza    Comercio     232934           17194
47 017 Venustiano Carranza    Industria    263065            1572
48 017 Venustiano Carranza    Servicios    288251            9894
   gasto_promedio_miles_por_ue
1   71.32
2  724.83
3   42.50
4   36.64
5  115.23
6   71.48
7   99.21
8   90.25
9  161.49
10  17.15
11 124.52
12  17.97
13  20.05
14 143.73
15  18.65
16  21.27
17 143.75
18  25.28
19  10.61
20  13.09
21  19.28
22   2.83
23  16.20
24   3.08
25  33.92
26 203.05
27 137.43
28   7.84
29 161.05
30   5.93
31  26.28
32  53.29
33  34.54
34  14.63
35  65.04
36   9.60
37  80.52
38 199.65
39  98.74
40  25.77
41  66.28
42 310.68
43 194.93
44 690.82
45 207.92
46  13.55
47 167.34
48  29.13

In [18]:
promedio_energia_tot <- datos %>% 
  group_by(municipio) %>% 
  summarise(
    gasto_total_miles = sum(gasto_energia_millones * 1000, na.rm = TRUE),
    total_ue = sum(ue_unidades_economicas, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  mutate(
    gasto_promedio_miles_por_ue = if_else(
      total_ue > 0,
      gasto_total_miles / total_ue,
      NA_real_
    )
  ) %>% 
  mutate(gasto_promedio_miles_por_ue = round(gasto_promedio_miles_por_ue, 2))
promedio_energia_tot

   municipio                  gasto_total_miles total_ue
1  002 Azcapotzalco           2039002           17098
2  003 Coyoacán               1336251           22648
3  004 Cuajimalpa de Morelos  1010347            8002
4  005 Gustavo A. Madero      1210885           46809
5  006 Iztacalco               502485           16013
6  007 Iztapalapa             2800579           82011
7  008 La Magdalena Contreras  111436            7714
8  009 Milpa Alta               27684            6894
9  010 Álvaro Obregón         2045439           22136
10 011 Tláhuac                 372643           16354
11 012 Tlalpan                 772079           24077
12 013 Xochimilco              314573           18792
13 014 Benito Juárez          2142264           21843
14 015 Cuauhtémoc             8382723           63196
15 016 Miguel Hidalgo         5281606           22496
16 017 Venustiano Carranza     784250           28660
   gasto_promedio_miles_por_ue
1  119.25
2   59.00
3  126.26
4   25.87
5   31.38
6   34.15
7   14.45
8    4.02
9   92.40
10  22.79
11  32.07
12  16.74
13  98.08
14 132.65
15 234.78
16  27.36